package:
  name:  propka
  version: {{ environ.get('BUILD_VERSION', "0.0.1" ) }}


build:
  number: {{ environ.get('BUILD_NUMBER', 0 ) }}

source:
  git_url: https://github.com/jensengroup/propka-3.1


 
requirements:
  build:
    - python
    - setuptools
  run:
    - python
   
about:
  license: "LGPL 2.1"
